# Generated by Django 2.2.6 on 2020-05-17 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='roadsign',
            name='img_template_url',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
